### ISSUE TITLE
lolog-ergm vignette attempts to fit an ergm specification that exhibits a phase transition.

### ISSUE THREAD

**Issue by krivit** [statnet/lolog#6]
In the estimation

https://github.com/statnet/lolog/blob/5fdd171bfed17be505ceb50e8f0f7aa4ee91456f/vignettes/lolog-ergm.Rmd#L116-L117

the choice of GWESP decay (0.25) exhibits a phase transition near the MLE. This can be seen in trace plots produced by
```r
fitukErgm <- ergm(ukFaculty ~ edges() + nodematch("GroupC") + nodefactor("GroupC", base=3) + gwesp(decay=.25, fixed=TRUE),
                  control=control.ergm(MCMC.runtime.traceplot=TRUE))
```

**Comment by ifellows** [comment]
Thanks. This model was supposed to be fit-able, but close to degenerate. Basically I backed off the gwesp decay until I got something that fit and had decent trace plots at the final iteration. Thus, the MLE is close to a phase transition by design.

Of course, ergm has gone through significant changes and so we should expect that convergence might not be achieved in newer versions due to unstable nature of the MCMCMLE process around phase transition points.

Do you have a suggestion for a best fit achievable by ergm for this data?

**Comment by krivit** [comment]
Off the top of my head,

* add mutuality
* use differential homophily
* reduce GWESP decay slightly

```
fitukErgm <- ergm(ukFaculty ~ edges() + mutual + nodematch("GroupC", diff=TRUE) + nodefactor("GroupC", base=3) + gwesp(.2, fix=TRUE))
```
seems to be a bit better behaved and runs between 1 and 3 minutes on my system.

More generally, there seems to be quite a bit of unaccounted-for degree heterogeneity in the model.

**Comment by krivit** [comment]
Following up on this, @ifellows, this has been messing up my reverse-dependency checks for the past few releases. I've suggested a possible improvement above (and I think it works pretty well with the original .25 decay as well on more recent versions of `ergm`). Can you please incorporate it?

**Comment by martinamorris** [comment]
watching.

**Comment by ifellows** [comment]
Suggested change has been added. Thanks.
